spring:
  application:
    name: spring-data-redis-test
  redis:
    type: REDIS_CLUSTER
    clientType: LETTUCE
    lettucecluster:
      nodes: 114.114.114.114:6380,114.114.114.114:6381,114.114.114.114:6382,114.114.114.114:6383,114.114.114.114:6384,114.114.114.114:6385
      maxRedirects: 6
      timeout: 2000  # 读取超时时间,ms
      password:
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 200
        maxWaitMillis: 1000
#    lettuce:
#      host: localhost
#      port: 6379
#      password: kuteredis
#      poolConfig:
#        maxActive: 100
#        maxIdle: 10
#        minIdle: 1
#        timeout: 3000
server:
  port: 8090
