spring:
  application:
    name: spring-data-redis-test
  redis:
    type: REDIS_CLUSTER
    clientType: LETTUCE
    lettucecluster:
      nodes: 172.30.13.76:6380,172.30.13.76:6381,172.30.13.76:6382,172.30.13.76:6383,172.30.13.76:6384,172.30.13.76:6385
      maxRedirects: 6
      timeout: 2000  # 读取超时时间,ms
      password:
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 200
        maxWaitMillis: 1000
#    lettuce:
#      host: 172.30.13.76
#      port: 6386
#      password: beike2018
#      poolConfig:
#        maxActive: 100
#        maxIdle: 10
#        minIdle: 1
#        timeout: 3000
server:
  port: 8090
