spring:
  application:
    name: spring-data-redis-test
  redis:
#    type: REDIS_CLUSTER
    clientType: LETTUCE
    lettucecluster:
      nodes: 192.168.1.4:7000,192.168.1.4:7001,192.168.1.4:7002,192.168.1.4:7003,192.168.1.4:7004,192.168.1.4:7005
      maxRedirects: 1
      timeout: 2000  # 读取超时时间,ms
      password:
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 200
        maxWaitMillis: 1000
#    lettuce:
#      host: localhost
#      port: 6379
#      password: kuteredis
#      poolConfig:
#        maxActive: 100
#        maxIdle: 10
#        minIdle: 1
#        timeout: 3000
server:
  port: 8090
