spring:
  application:
    name: spring-data-redis-test
  redis:
#    type: REDIS_CLUSTER
#    clientType: LETTUCE
    lettucecluster:
      nodes: 114.114.114.114:7000,114.114.114.114:7001,114.114.114.114:7002,114.114.114.114:7003,114.114.114.114:7004,114.114.114.114:7005
      maxRedirects: 1
      timeout: 2000  # 读取超时时间,ms
      password:
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 200
        maxWaitMillis: 1000
#    lettuce:
#      host: localhost
#      port: 6379
#      password: kuteredis
#      poolConfig:
#        maxActive: 100
#        maxIdle: 10
#        minIdle: 1
#        timeout: 3000
server:
  port: 8090
